### ISSUE TITLE
Friend list and discord Settings

### ISSUE THREAD

**Issue by JohannKili** [Eight-P/BD.8P#20]
### T1 Issue report:

For whatever reason, I feel like it's broken, idk why

![Screenshot 2023-10-17 223849](https://github.com/Eight-P/BD.8P/assets/139029143/658732d9-f3f6-4d37-b1c8-6243127cac25)
![image](https://github.com/Eight-P/BD.8P/assets/139029143/735a0394-3848-45b1-8734-f82e6d83f781)

### T1 version:

0.8

### Discord client:

PTB

### Platform:

Windows

### Discord Mod:

BetterDiscord

**Comment by Eight-P** [comment]
Yeah, sometimes when Discord makes an update it can break parts of the theme.

Usually I fix these issues only once they occur on stable. 
Otherwise, I'd have to maintain 3 different versions of the theme and deal with some other issues.

I recommend using the stable client to avoid stuff like that.

It may still break for a moment, but I usually try to fix major stuff within a day.
On Canary or PTB it may be broken for longer periods as I wait for the update to hit stable.

Thanks for letting me know about the issue tho. I got a fix ready to go.
Sorry for the inconvenience.

**Comment by RileyVRC** [comment]
> Yeah, sometimes when Discord makes an update it can break parts of the theme.
> 
> Usually I fix these issues only once they occur on stable. Otherwise, I'd have to maintain 3 different versions of the theme and deal with some other issues.
> 
> I recommend using the stable client to avoid stuff like that.
> 
> It may still break for a moment, but I usually try to fix major stuff within a day. On Canary or PTB it may be broken for longer periods as I wait for the update to hit stable.
> 
> Thanks for letting me know about the issue tho. I got a fix ready to go. Sorry for the inconvenience.

The issue has now happened on stable, it's probably time to push the update...

![image_2023-10-17_234440935](https://github.com/Eight-P/BD.8P/assets/49098146/c0058ca7-99e8-42ec-b7d6-1ca9fbd5e3ce)
![image_2023-10-17_234520570](https://github.com/Eight-P/BD.8P/assets/49098146/6e647dd1-94c4-4978-b8f7-a71f6c8682d4)

**Comment by Eight-P** [comment]
Yup, should be fixed now.

**Comment by JohannKili** [comment]
> Yup, should be fixed now.

thx
